import type { MinionDefinition, Tribe } from "./types.ts";

export const TRIBE_NAMES: Readonly<Record<Tribe, string>> = {
  wild: "荒野",
  construct: "构装",
  ember: "余烬",
  tide: "潮汐",
  astral: "星界",
  neutral: "中立",
};

/**
 * Original names, text, and stat lines for this project. The roster is kept as
 * data so balancing never needs changes to the battle engine.
 */
export const MINION_DEFINITIONS: readonly MinionDefinition[] = [
  // Tier 1
  {
    id: "moss-pup",
    name: "苔原幼兽",
    tier: 1,
    tribe: "wild",
    attack: 2,
    health: 2,
    description: "一只可靠的荒野幼兽。",
  },
  {
    id: "scrap-scout",
    name: "废料侦察机",
    tier: 1,
    tribe: "construct",
    attack: 1,
    health: 3,
    divineShield: true,
    description: "护盾。",
  },
  {
    id: "coal-sprinter",
    name: "煤火疾行者",
    tier: 1,
    tribe: "ember",
    attack: 3,
    health: 1,
    description: "攻击迅猛但十分脆弱。",
  },
  {
    id: "foam-squire",
    name: "泡沫侍从",
    tier: 1,
    tribe: "tide",
    attack: 1,
    health: 4,
    taunt: true,
    description: "守卫。",
  },
  {
    id: "starling",
    name: "微光星雀",
    tier: 1,
    tribe: "astral",
    attack: 2,
    health: 1,
    battlecry: [
      { kind: "buff", target: "randomFriendly", attack: 1, health: 1 },
    ],
    description: "入场：随机使一个其他友方单位获得 +1/+1。",
  },
  {
    id: "lane-warden",
    name: "驿道守卫",
    tier: 1,
    tribe: "neutral",
    attack: 1,
    health: 5,
    taunt: true,
    description: "守卫。",
  },

  // Tier 2
  {
    id: "pack-drummer",
    name: "兽群鼓手",
    tier: 2,
    tribe: "wild",
    attack: 3,
    health: 3,
    battlecry: [
      {
        kind: "buff",
        target: "friendlyTribe",
        tribe: "wild",
        attack: 1,
        health: 0,
      },
    ],
    description: "入场：使你的荒野单位获得 +1 攻击力。",
  },
  {
    id: "rivet-guardian",
    name: "铆钉护卫",
    tier: 2,
    tribe: "construct",
    attack: 2,
    health: 4,
    taunt: true,
    divineShield: true,
    description: "守卫，护盾。",
  },
  {
    id: "ember-feeder",
    name: "炉膛饲火者",
    tier: 2,
    tribe: "ember",
    attack: 4,
    health: 3,
    battlecry: [{ kind: "buff", target: "self", attack: 1, health: 1 }],
    description: "入场：获得 +1/+1。",
  },
  {
    id: "tide-binder",
    name: "系潮人",
    tier: 2,
    tribe: "tide",
    attack: 2,
    health: 5,
    battlecry: [
      { kind: "buff", target: "randomFriendly", attack: 1, health: 2 },
    ],
    description: "入场：随机使一个其他友方单位获得 +1/+2。",
  },
  {
    id: "comet-novice",
    name: "彗尾学徒",
    tier: 2,
    tribe: "astral",
    attack: 3,
    health: 3,
    deathrattle: [{ kind: "summon", definitionId: "starling", count: 1 }],
    description: "毁灭时：召唤一个微光星雀。",
  },
  {
    id: "caravan-cook",
    name: "旅队炊事员",
    tier: 2,
    tribe: "neutral",
    attack: 3,
    health: 4,
    battlecry: [
      { kind: "buff", target: "randomFriendly", attack: 1, health: 2 },
    ],
    description: "入场：随机使一个其他友方单位获得 +1/+2。",
  },

  // Tier 3
  {
    id: "thornback-alpha",
    name: "棘背领兽",
    tier: 3,
    tribe: "wild",
    attack: 5,
    health: 4,
    battlecry: [
      {
        kind: "buff",
        target: "friendlyTribe",
        tribe: "wild",
        attack: 1,
        health: 1,
      },
    ],
    description: "入场：使你的荒野单位获得 +1/+1。",
  },
  {
    id: "clockwork-egg",
    name: "发条育舱",
    tier: 3,
    tribe: "construct",
    attack: 0,
    health: 6,
    taunt: true,
    deathrattle: [{ kind: "summon", definitionId: "gearling-token", count: 2 }],
    description: "守卫。毁灭时：召唤两个 2/2 齿轮仔。",
  },
  {
    id: "cinder-duelist",
    name: "烬刃决斗家",
    tier: 3,
    tribe: "ember",
    attack: 6,
    health: 3,
    divineShield: true,
    description: "护盾。",
  },
  {
    id: "reef-caller",
    name: "礁群唤潮者",
    tier: 3,
    tribe: "tide",
    attack: 4,
    health: 5,
    deathrattle: [{ kind: "summon", definitionId: "foam-squire", count: 2 }],
    description: "毁灭时：召唤两个泡沫侍从。",
  },
  {
    id: "orbit-seer",
    name: "环轨观星者",
    tier: 3,
    tribe: "astral",
    attack: 3,
    health: 6,
    battlecry: [
      {
        kind: "buff",
        target: "friendlyTribe",
        tribe: "astral",
        attack: 1,
        health: 1,
      },
    ],
    description: "入场：使你的星界单位获得 +1/+1。",
  },
  {
    id: "banner-smith",
    name: "旌旗铁匠",
    tier: 3,
    tribe: "neutral",
    attack: 4,
    health: 5,
    taunt: true,
    battlecry: [
      { kind: "buff", target: "otherFriendly", attack: 1, health: 0 },
    ],
    description: "守卫。入场：使其他友方单位获得 +1 攻击力。",
  },

  // Tier 4
  {
    id: "grove-matriarch",
    name: "林冠母兽",
    tier: 4,
    tribe: "wild",
    attack: 5,
    health: 7,
    deathrattle: [{ kind: "summon", definitionId: "moss-pup", count: 2 }],
    description: "毁灭时：召唤两个苔原幼兽。",
  },
  {
    id: "bronze-colossus",
    name: "青铜壁垒",
    tier: 4,
    tribe: "construct",
    attack: 6,
    health: 7,
    taunt: true,
    divineShield: true,
    description: "守卫，护盾。",
  },
  {
    id: "furnace-captain",
    name: "熔炉队长",
    tier: 4,
    tribe: "ember",
    attack: 7,
    health: 5,
    battlecry: [
      {
        kind: "buff",
        target: "friendlyTribe",
        tribe: "ember",
        attack: 2,
        health: 1,
      },
    ],
    description: "入场：使你的余烬单位获得 +2/+1。",
  },
  {
    id: "deepwater-monarch",
    name: "深水领主",
    tier: 4,
    tribe: "tide",
    attack: 4,
    health: 9,
    taunt: true,
    description: "守卫。",
  },
  {
    id: "nova-conductor",
    name: "新星指挥家",
    tier: 4,
    tribe: "astral",
    attack: 5,
    health: 6,
    battlecry: [
      { kind: "buff", target: "allFriendly", attack: 1, health: 1 },
    ],
    description: "入场：使所有友方单位获得 +1/+1。",
  },
  {
    id: "mirror-knight",
    name: "镜甲骑士",
    tier: 4,
    tribe: "neutral",
    attack: 6,
    health: 6,
    divineShield: true,
    description: "护盾。",
  },

  // Tier 5
  {
    id: "ancient-stampede",
    name: "远古奔踏者",
    tier: 5,
    tribe: "wild",
    attack: 8,
    health: 8,
    deathrattle: [{ kind: "summon", definitionId: "thornback-alpha", count: 1 }],
    description: "毁灭时：召唤一个棘背领兽。",
  },
  {
    id: "assembly-sovereign",
    name: "装配主脑",
    tier: 5,
    tribe: "construct",
    attack: 7,
    health: 9,
    battlecry: [
      {
        kind: "buff",
        target: "friendlyTribe",
        tribe: "construct",
        attack: 2,
        health: 2,
      },
    ],
    description: "入场：使你的构装单位获得 +2/+2。",
  },
  {
    id: "magma-regent",
    name: "熔岩摄政",
    tier: 5,
    tribe: "ember",
    attack: 10,
    health: 6,
    divineShield: true,
    description: "护盾。",
  },
  {
    id: "abyssal-chorus",
    name: "渊潮合唱者",
    tier: 5,
    tribe: "tide",
    attack: 6,
    health: 11,
    deathrattle: [
      { kind: "buff", target: "allFriendly", attack: 2, health: 2 },
    ],
    description: "毁灭时：使所有友方单位获得 +2/+2。",
  },
  {
    id: "galaxy-shepherd",
    name: "银河牧者",
    tier: 5,
    tribe: "astral",
    attack: 7,
    health: 8,
    deathrattle: [{ kind: "summon", definitionId: "comet-novice", count: 2 }],
    description: "毁灭时：召唤两个彗尾学徒。",
  },
  {
    id: "citadel-giant",
    name: "城塞巨像",
    tier: 5,
    tribe: "neutral",
    attack: 9,
    health: 10,
    taunt: true,
    description: "守卫。",
  },

  // Tier 6
  {
    id: "worldroot-behemoth",
    name: "世界根巨兽",
    tier: 6,
    tribe: "wild",
    attack: 12,
    health: 12,
    taunt: true,
    deathrattle: [{ kind: "summon", definitionId: "moss-pup", count: 3 }],
    description: "守卫。毁灭时：召唤三个苔原幼兽。",
  },
  {
    id: "perfect-automaton",
    name: "完铸自动机",
    tier: 6,
    tribe: "construct",
    attack: 10,
    health: 10,
    divineShield: true,
    deathrattle: [{ kind: "summon", definitionId: "gearling-token", count: 2 }],
    description: "护盾。毁灭时：召唤两个齿轮仔。",
  },
  {
    id: "sunforge-tyrant",
    name: "铸日暴君",
    tier: 6,
    tribe: "ember",
    attack: 14,
    health: 8,
    battlecry: [
      { kind: "buff", target: "allFriendly", attack: 2, health: 2 },
    ],
    description: "入场：使所有友方单位获得 +2/+2。",
  },
  {
    id: "leviathan-of-the-deep",
    name: "无底海兽",
    tier: 6,
    tribe: "tide",
    attack: 9,
    health: 15,
    taunt: true,
    deathrattle: [{ kind: "summon", definitionId: "reef-caller", count: 1 }],
    description: "守卫。毁灭时：召唤一个礁群唤潮者。",
  },
  {
    id: "supernova-herald",
    name: "超新星先驱",
    tier: 6,
    tribe: "astral",
    attack: 11,
    health: 11,
    deathrattle: [{ kind: "summon", definitionId: "comet-novice", count: 2 }],
    description: "毁灭时：召唤两个彗尾学徒。",
  },
  {
    id: "crownless-champion",
    name: "无冠冠军",
    tier: 6,
    tribe: "neutral",
    attack: 13,
    health: 13,
    divineShield: true,
    description: "护盾。",
  },

  // Combat-only tokens. They are definitions for rendering and effects but are
  // never inserted into the shared tavern pool.
  {
    id: "gearling-token",
    name: "齿轮仔",
    tier: 1,
    tribe: "construct",
    attack: 2,
    health: 2,
    description: "由构装单位召唤的战斗单位。",
    collectible: false,
  },
] as const;

export const MINION_BY_ID: Readonly<Record<string, MinionDefinition>> =
  Object.freeze(
    Object.fromEntries(
      MINION_DEFINITIONS.map((definition) => [definition.id, definition]),
    ),
  );

export function getMinionDefinition(id: string): MinionDefinition {
  const definition = MINION_BY_ID[id];
  if (!definition) {
    throw new Error(`Unknown minion definition: ${id}`);
  }
  return definition;
}
