import type { MinionDefinition, Tribe } from "./types.ts";

export const CLASSIC_ROSTER_VERSION = "classic-nostalgia-2026-07";

export const TRIBE_NAMES: Readonly<Record<Tribe, string>> = {
  beast: "野兽",
  mech: "机械",
  demon: "恶魔",
  murloc: "鱼人",
  dragon: "龙",
  pirate: "海盗",
  neutral: "中立",
};

/**
 * A deliberately stable nostalgia pool rather than the live rotating pool.
 * Names, art CardIDs and signature mechanics match recognizable Battlegrounds
 * cards. Some tiers use their best-known classic placement.
 */
export const MINION_DEFINITIONS: readonly MinionDefinition[] = [
  // Tier 1
  {
    id: "alleycat",
    cardId: "BG_CFM_315",
    name: "雄斑虎",
    tier: 1,
    tribe: "beast",
    attack: 1,
    health: 1,
    description: "战吼：召唤一头1/1的雌斑虎。",
    battlecry: [{ kind: "summon", definitionId: "tabbycat-token", count: 1 }],
  },
  {
    id: "murloc-tidehunter",
    cardId: "EX1_506",
    name: "鱼人猎潮者",
    tier: 1,
    tribe: "murloc",
    attack: 2,
    health: 1,
    description: "战吼：召唤一个1/1的鱼人斥候。",
    battlecry: [
      { kind: "summon", definitionId: "murloc-scout-token", count: 1 },
    ],
  },
  {
    id: "dragonspawn-lieutenant",
    cardId: "BGS_039",
    name: "龙人军官",
    tier: 1,
    tribe: "dragon",
    attack: 2,
    health: 3,
    taunt: true,
    description: "嘲讽",
  },
  {
    id: "vulgar-homunculus",
    cardId: "LOOT_013",
    name: "粗俗的矮劣魔",
    tier: 1,
    tribe: "demon",
    attack: 2,
    health: 4,
    taunt: true,
    description: "嘲讽。战吼：对你的英雄造成2点伤害。",
    battlecry: [{ kind: "damageHero", amount: 2 }],
  },
  {
    id: "wrath-weaver",
    cardId: "BGS_004",
    name: "愤怒编织者",
    tier: 1,
    tribe: "demon",
    attack: 1,
    health: 3,
    description:
      "在你使用一张恶魔牌后，对你的英雄造成1点伤害并获得+2/+2。",
    afterFriendlyPlayed: {
      tribe: "demon",
      attack: 2,
      health: 2,
      heroDamage: 1,
    },
  },
  {
    id: "scallywag",
    cardId: "BGS_061",
    name: "海盗无赖",
    tier: 1,
    tribe: "pirate",
    attack: 3,
    health: 1,
    description: "亡语：召唤一个1/1的海盗并使其立即发起攻击。",
    deathrattle: [
      {
        kind: "summon",
        definitionId: "sky-pirate-token",
        count: 1,
        immediateAttack: true,
      },
    ],
  },

  // Tier 2
  {
    id: "harvest-golem",
    cardId: "BG_EX1_556",
    name: "麦田傀儡",
    tier: 2,
    tribe: "mech",
    attack: 2,
    health: 3,
    description: "亡语：召唤一个2/1的损坏的傀儡。",
    deathrattle: [
      { kind: "summon", definitionId: "damaged-golem-token", count: 1 },
    ],
  },
  {
    id: "kaboom-bot",
    cardId: "BG_BOT_606",
    name: "爆爆机器人",
    tier: 2,
    tribe: "mech",
    attack: 2,
    health: 2,
    description: "亡语：随机对一个敌方随从造成4点伤害。",
    deathrattle: [{ kind: "damageEnemy", amount: 4, target: "random" }],
  },
  {
    id: "spawn-of-nzoth",
    cardId: "BG_OG_256",
    name: "恩佐斯的子嗣",
    tier: 2,
    tribe: "neutral",
    attack: 2,
    health: 2,
    description: "亡语：使你的所有随从获得+1/+1。",
    deathrattle: [
      { kind: "buff", target: "allFriendly", attack: 1, health: 1 },
    ],
  },
  {
    id: "selfless-hero",
    cardId: "BG_OG_221",
    name: "无私的英雄",
    tier: 2,
    tribe: "neutral",
    attack: 2,
    health: 1,
    description: "亡语：随机使一个友方随从获得圣盾。",
    deathrattle: [{ kind: "grantShield", target: "randomFriendly" }],
  },
  {
    id: "nathrezim-overseer",
    cardId: "BGS_001",
    name: "纳斯雷兹姆监工",
    tier: 2,
    tribe: "demon",
    attack: 2,
    health: 4,
    description: "战吼：随机使一个其他友方恶魔获得+2/+2。",
    battlecry: [
      {
        kind: "buff",
        target: "randomFriendlyTribe",
        tribe: "demon",
        attack: 2,
        health: 2,
      },
    ],
  },
  {
    id: "murloc-warleader",
    cardId: "BG_EX1_507",
    name: "鱼人领军",
    tier: 2,
    tribe: "murloc",
    attack: 3,
    health: 3,
    description: "你的其他鱼人拥有+2攻击力。",
    aura: { tribe: "murloc", attack: 2, health: 0, otherOnly: true },
  },

  // Tier 3
  {
    id: "bronze-warden",
    cardId: "BGS_034",
    name: "青铜守卫",
    tier: 3,
    tribe: "dragon",
    attack: 2,
    health: 1,
    divineShield: true,
    reborn: true,
    description: "圣盾，复生",
  },
  {
    id: "rat-pack",
    cardId: "BG_CFM_316",
    name: "瘟疫鼠群",
    tier: 3,
    tribe: "beast",
    attack: 2,
    health: 2,
    description: "亡语：召唤若干个1/1的老鼠，数量等同于本随从的攻击力。",
    deathrattle: [
      {
        kind: "summon",
        definitionId: "rat-token",
        count: "sourceAttack",
      },
    ],
  },
  {
    id: "deflect-o-bot",
    cardId: "BGS_071",
    name: "偏折机器人",
    tier: 3,
    tribe: "mech",
    attack: 3,
    health: 2,
    divineShield: true,
    description:
      "圣盾。在战斗阶段中，每当你召唤一个机械，便获得+2攻击力和圣盾。",
    afterFriendlySummoned: {
      tribe: "mech",
      attack: 2,
      grantShield: true,
    },
  },
  {
    id: "soul-juggler",
    cardId: "BGS_002",
    name: "灵魂杂耍者",
    tier: 3,
    tribe: "demon",
    attack: 3,
    health: 5,
    description:
      "在一个友方恶魔死亡后，对生命值最高的敌方随从造成4点伤害。",
    afterFriendlyDied: {
      tribe: "demon",
      damageEnemy: 4,
      damageTarget: "highestHealth",
    },
  },
  {
    id: "screwjank-clunker",
    cardId: "GVG_055",
    name: "废旧螺栓机甲",
    tier: 3,
    tribe: "mech",
    attack: 2,
    health: 5,
    description: "战吼：随机使一个其他友方机械获得+2/+2。",
    battlecry: [
      {
        kind: "buff",
        target: "randomFriendlyTribe",
        tribe: "mech",
        attack: 2,
        health: 2,
      },
    ],
  },
  {
    id: "houndmaster",
    cardId: "DS1_070",
    name: "驯兽师",
    tier: 3,
    tribe: "neutral",
    attack: 4,
    health: 3,
    description: "战吼：随机使一个友方野兽获得+2/+2和嘲讽。",
    battlecry: [
      {
        kind: "buff",
        target: "randomFriendlyTribe",
        tribe: "beast",
        attack: 2,
        health: 2,
        taunt: true,
      },
    ],
  },

  // Tier 4
  {
    id: "cave-hydra",
    cardId: "BG_LOOT_078",
    name: "洞穴多头蛇",
    tier: 4,
    tribe: "beast",
    attack: 2,
    health: 4,
    cleave: true,
    description: "同时对其攻击目标相邻的随从造成伤害。",
  },
  {
    id: "security-rover",
    cardId: "BOT_218",
    name: "安保巡游者",
    tier: 4,
    tribe: "mech",
    attack: 2,
    health: 6,
    description: "每当本随从受到伤害，召唤一个2/3并具有嘲讽的机械。",
    afterSelfDamaged: [
      { kind: "summon", definitionId: "guard-bot-token", count: 1 },
    ],
  },
  {
    id: "mechano-egg",
    cardId: "BOT_537",
    name: "机械蛋",
    tier: 4,
    tribe: "mech",
    attack: 0,
    health: 5,
    description: "亡语：召唤一个8/8的机械暴龙。",
    deathrattle: [
      { kind: "summon", definitionId: "robosaur-token", count: 1 },
    ],
  },
  {
    id: "savannah-highmane",
    cardId: "BG_EX1_534",
    name: "长鬃草原狮",
    tier: 4,
    tribe: "beast",
    attack: 6,
    health: 5,
    description: "亡语：召唤两只2/2的土狼。",
    deathrattle: [
      { kind: "summon", definitionId: "hyena-token", count: 2 },
    ],
  },
  {
    id: "defender-of-argus",
    cardId: "EX1_093",
    name: "阿古斯防御者",
    tier: 4,
    tribe: "neutral",
    attack: 3,
    health: 3,
    description: "战吼：使相邻的随从获得+1/+1和嘲讽。",
    battlecry: [
      {
        kind: "buff",
        target: "adjacentFriendly",
        attack: 1,
        health: 1,
        taunt: true,
      },
    ],
  },
  {
    id: "junkbot",
    cardId: "GVG_106",
    name: "回收机器人",
    tier: 4,
    tribe: "mech",
    attack: 1,
    health: 5,
    description: "每当一个友方机械死亡，便获得+2/+2。",
    afterFriendlyDied: { tribe: "mech", attack: 2, health: 2 },
  },

  // Tier 5
  {
    id: "titus-rivendare",
    cardId: "BG25_354",
    name: "提图斯·瑞文戴尔",
    tier: 5,
    tribe: "neutral",
    attack: 1,
    health: 7,
    description: "你的亡语额外触发一次。",
    extraDeathrattles: 1,
  },
  {
    id: "brann-bronzebeard",
    cardId: "BG_LOE_077",
    name: "布莱恩·铜须",
    tier: 5,
    tribe: "neutral",
    attack: 2,
    health: 4,
    description: "你的战吼会触发两次。",
    extraBattlecries: 1,
  },
  {
    id: "lightfang-enforcer",
    cardId: "BGS_009",
    name: "光牙执行者",
    tier: 5,
    tribe: "neutral",
    attack: 8,
    health: 8,
    description: "在你的回合结束时，使每个类型的各一个友方随从获得+4/+4。",
    endOfTurn: { kind: "onePerTribe", attack: 4, health: 4 },
  },
  {
    id: "kangors-apprentice",
    cardId: "BGS_012",
    name: "坎格尔的学徒",
    tier: 5,
    tribe: "neutral",
    attack: 3,
    health: 6,
    description: "亡语：召唤你本场战斗中最先死亡的2个机械的原始版复制。",
    deathrattle: [{ kind: "resummonMechs", count: 2 }],
  },
  {
    id: "annihilan-battlemaster",
    cardId: "BGS_010",
    name: "安尼赫兰战场军官",
    tier: 5,
    tribe: "demon",
    attack: 3,
    health: 1,
    description: "战吼：你的英雄每缺失1点生命值，便获得+1生命值。",
    battlecry: [{ kind: "gainMissingHealth", multiplier: 1 }],
  },
  {
    id: "voidlord",
    cardId: "LOOT_368",
    name: "虚空领主",
    tier: 5,
    tribe: "demon",
    attack: 3,
    health: 9,
    taunt: true,
    description: "嘲讽。亡语：召唤三个1/3并具有嘲讽的恶魔。",
    deathrattle: [
      { kind: "summon", definitionId: "voidwalker-token", count: 3 },
    ],
  },

  // Tier 6
  {
    id: "goldrinn",
    cardId: "BGS_018",
    name: "巨狼戈德林",
    tier: 6,
    tribe: "beast",
    attack: 8,
    health: 8,
    description: "亡语：在本场战斗的剩余时间内，你的野兽拥有+8/+8。",
    deathrattle: [
      {
        kind: "buff",
        target: "friendlyTribe",
        tribe: "beast",
        attack: 8,
        health: 8,
      },
    ],
  },
  {
    id: "ghastcoiler",
    cardId: "BGS_008",
    name: "阴森巨蟒",
    tier: 6,
    tribe: "beast",
    attack: 7,
    health: 7,
    description: "亡语：随机召唤两个亡语随从。",
    deathrattle: [{ kind: "summonRandomDeathrattle", count: 2 }],
  },
  {
    id: "foe-reaper-4000",
    cardId: "BG_GVG_113",
    name: "死神4000型",
    tier: 6,
    tribe: "mech",
    attack: 6,
    health: 9,
    cleave: true,
    description: "同时对其攻击目标相邻的随从造成伤害。",
  },
  {
    id: "zapp-slywick",
    cardId: "BGS_022",
    name: "扎普·斯里维克",
    tier: 6,
    tribe: "neutral",
    attack: 11,
    health: 22,
    windfury: true,
    alwaysAttacksLowestAttack: true,
    description: "风怒。本随从总会攻击攻击力最低的敌方随从。",
  },
  {
    id: "maexxna",
    cardId: "FP1_010",
    name: "迈克斯纳",
    tier: 6,
    tribe: "beast",
    attack: 2,
    health: 8,
    poisonous: true,
    description: "剧毒",
  },
  {
    id: "mama-bear",
    cardId: "BGS_021",
    name: "熊妈妈",
    tier: 6,
    tribe: "beast",
    attack: 6,
    health: 6,
    description: "每当你召唤一只野兽，使其获得+6/+6。",
    afterFriendlySummoned: { tribe: "beast", attack: 6, health: 6 },
  },

  // Combat/recruit tokens use their own Hearthstone CardIDs so their portraits
  // remain recognizable instead of reusing the parent minion's artwork.
  {
    id: "tabbycat-token",
    cardId: "BG_CFM_315t",
    name: "雌斑虎",
    tier: 1,
    tribe: "beast",
    attack: 1,
    health: 1,
    description: "由雄斑虎召唤。",
    collectible: false,
  },
  {
    id: "murloc-scout-token",
    cardId: "EX1_506a",
    name: "鱼人斥候",
    tier: 1,
    tribe: "murloc",
    attack: 1,
    health: 1,
    description: "由鱼人猎潮者召唤。",
    collectible: false,
  },
  {
    id: "sky-pirate-token",
    cardId: "BGS_061t",
    name: "空中海盗",
    tier: 1,
    tribe: "pirate",
    attack: 1,
    health: 1,
    description: "由海盗无赖召唤并立即攻击。",
    collectible: false,
  },
  {
    id: "damaged-golem-token",
    cardId: "BG_EX1_556t",
    name: "损坏的傀儡",
    tier: 1,
    tribe: "mech",
    attack: 2,
    health: 1,
    description: "由麦田傀儡召唤。",
    collectible: false,
  },
  {
    id: "rat-token",
    cardId: "BG_CFM_316t",
    name: "老鼠",
    tier: 1,
    tribe: "beast",
    attack: 1,
    health: 1,
    description: "由瘟疫鼠群召唤。",
    collectible: false,
  },
  {
    id: "guard-bot-token",
    cardId: "BOT_218t",
    name: "警卫机器人",
    tier: 1,
    tribe: "mech",
    attack: 2,
    health: 3,
    taunt: true,
    description: "嘲讽。由安保巡游者召唤。",
    collectible: false,
  },
  {
    id: "robosaur-token",
    cardId: "BOT_537t",
    name: "机械暴龙",
    tier: 1,
    tribe: "mech",
    attack: 8,
    health: 8,
    description: "由机械蛋召唤。",
    collectible: false,
  },
  {
    id: "hyena-token",
    cardId: "BG_EX1_534t",
    name: "土狼",
    tier: 1,
    tribe: "beast",
    attack: 2,
    health: 2,
    description: "由长鬃草原狮召唤。",
    collectible: false,
  },
  {
    id: "voidwalker-token",
    cardId: "BG_CS2_065",
    name: "虚空行者",
    tier: 1,
    tribe: "demon",
    attack: 1,
    health: 3,
    taunt: true,
    description: "嘲讽。由虚空领主召唤。",
    collectible: false,
  },
] as const;

export const MINION_BY_ID: Readonly<Record<string, MinionDefinition>> =
  Object.freeze(
    Object.fromEntries(
      MINION_DEFINITIONS.map((definition) => [definition.id, definition]),
    ),
  );

export function getMinionDefinition(id: string): MinionDefinition {
  const definition = MINION_BY_ID[id];
  if (!definition) {
    throw new Error(`Unknown minion definition: ${id}`);
  }
  return definition;
}
