import {
  AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
  buildAiVideoDecisionCorpus,
  type AiVideoDecisionWindow,
} from "./ai-video-decision-corpus.ts";

export const AI_VIDEO_CORPUS_REVIEWER =
  "codex-multi-agent-frame-review-2026-08-07" as const;
export const AI_VIDEO_CORPUS_SECOND_REVIEWER =
  "codex-independent-frame-review-2026-08-07-a" as const;
export const AI_VIDEO_CORPUS_DOUBLE_REVIEWER =
  `${AI_VIDEO_CORPUS_REVIEWER};${AI_VIDEO_CORPUS_SECOND_REVIEWER}` as const;

/**
 * Human-reviewed decision windows from runtime-compatible gameplay videos.
 * Omitted visible fields were not clear enough to encode as exact values.
 */
export const AI_VIDEO_DECISION_WINDOWS = Object.freeze([
  // BV11BNb6qEgy
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv11bnb6qegy-063650-upgrade",
    bvid: "BV11BNb6qEgy",
    startMs: 63_400,
    decisionMs: 63_650,
    endMs: 64_750,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示玩家有4金币，升级按钮费用为4，升级按钮处于可点击状态。",
    actionStatement: "玩家明确点击酒馆升级；连续帧显示金币由4变为0且酒馆等级发生变化。",
    reviewRationale: "点击位置、升级费用、金币扣除和等级变化均在连续画面中可见。",
    visible: { gold: 4, upgradeCost: 4 },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级按钮显示费用4且玩家拥有4金币，立即升级与暂缓升级均合法。",
        evidenceMode: "direct",
        interpretation: "可见的按钮点击、金币扣除和等级变化直接证明立即升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv11bnb6qegy-080050-refresh",
    bvid: "BV11BNb6qEgy",
    startMs: 79_000,
    decisionMs: 80_050,
    endMs: 80_750,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示玩家有5金币、刷新费用为1，刷新前商店中有5个实体。",
    actionStatement: "玩家明确点击刷新；整排商店内容更换且金币由5变为4。",
    reviewRationale: "刷新按钮、旧商店、金币扣除和新商店均在连续帧中清晰可见。",
    visible: { gold: 5, refreshCurrency: "gold", refreshCost: 1 },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新按钮显示费用1且玩家拥有5金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少1且完整商店更换，直接证明执行一次刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv11bnb6qegy-081600-buy-over-upgrade",
    bvid: "BV11BNb6qEgy",
    startMs: 80_750,
    decisionMs: 81_600,
    endMs: 82_000,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示玩家有4金币，升级费用为4，升级按钮处于可点击状态。",
    actionStatement: "玩家明确购买一个3费商店随从，购买后金币由4变为1，未进行升级。",
    reviewRationale: "购买拖拽、商店槽位变化及金币4到1构成明确的互斥动作边界。",
    visible: { gold: 4, upgradeCost: 4 },
    labels: [
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.99,
        legalStatement: "升级按钮显示费用4且玩家拥有4金币，立即升级原本合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 4,
          after: 1,
          required: 4,
        },
        interpretation: "玩家明确把3金币用于购买随从并使余额降至1，因此在该边界选择暂缓升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv11bnb6qegy-121600-buy-over-upgrade",
    bvid: "BV11BNb6qEgy",
    startMs: 120_500,
    decisionMs: 121_600,
    endMs: 122_100,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示玩家有7/7金币且酒馆升级费用为5，立即升级处于合法状态。",
    actionStatement: "玩家明确购买商店右侧的3费侦查员随从，商店槽位消失且金币由7变为4。",
    reviewRationale: "明确的3费购买把金币从7降至4，使原本合法的5费升级立即不再合法。",
    visible: { gold: 7, upgradeCost: 5 },
    labels: [
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.99,
        legalStatement: "升级费用为5且玩家有7金币，动作前立即升级合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 7,
          after: 4,
          required: 5,
        },
        interpretation: "购买3费侦查员使金币降至4，升级在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv11bnb6qegy-134250-freeze",
    bvid: "BV11BNb6qEgy",
    startMs: 133_500,
    decisionMs: 134_250,
    endMs: 135_000,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "冻结前商店实体没有冰层，画面中的0费冻结按钮处于可用状态。",
    actionStatement: "玩家明确点击冻结按钮，随后商店实体出现完整的结冰视觉效果。",
    reviewRationale: "冻结前状态、按钮点击及结冰结果均由连续帧直接支持。",
    visible: { currentlyFrozen: false },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.99,
        legalStatement: "冻结按钮显示0费且商店此前未冻结，冻结和保持未冻结均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击后的整店结冰动画直接证明选择冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv11bnb6qegy-175450-combat-unfrozen",
    bvid: "BV11BNb6qEgy",
    startMs: 174_000,
    decisionMs: 175_450,
    endMs: 176_000,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示商店未冻结，0费冻结按钮在招募阶段结束前仍然可用。",
    actionStatement: "玩家没有冻结商店，画面随后明确切换到战斗阶段。",
    reviewRationale: "未冻结商店、合法按钮和进入战斗的回合边界共同支持负标签。",
    visible: { currentlyFrozen: false },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.97,
        legalStatement: "商店未冻结且冻结按钮显示0费，冻结原本合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "招募阶段明确结束并进入战斗，且商店始终未结冰，因此选择保持未冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv11bnb6qegy-211550-upgrade",
    bvid: "BV11BNb6qEgy",
    startMs: 210_000,
    decisionMs: 211_550,
    endMs: 213_250,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示玩家有10金币，升级按钮可点击且金币足以支付显示的升级费用。",
    actionStatement: "玩家明确点击升级，金币显著下降，同时酒馆等级和商店容量发生变化。",
    reviewRationale: "升级按钮点击、金币下降、等级标识和商店容量变化在连续帧中可见。",
    visible: { gold: 10 },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级按钮在10金币状态下清晰可用，立即升级与暂缓均为合法选择。",
        evidenceMode: "direct",
        interpretation: "点击及升级后的等级和容量变化直接证明立即升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv11bnb6qegy-217750-refresh",
    bvid: "BV11BNb6qEgy",
    startMs: 216_500,
    decisionMs: 217_750,
    endMs: 218_500,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示玩家有1金币、刷新费用为1，当前商店包含6个实体。",
    actionStatement: "玩家明确点击刷新，金币由1变为0并出现一整排新的6格商店。",
    reviewRationale: "点击、金币扣除及完整新商店在连续帧中清晰可辨。",
    visible: { gold: 1, refreshCurrency: "gold", refreshCost: 1 },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.98,
        legalStatement: "刷新费用为1且玩家恰有1金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币归零且整店更换，直接证明执行一次刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv11bnb6qegy-278350-refresh",
    bvid: "BV11BNb6qEgy",
    startMs: 277_500,
    decisionMs: 278_350,
    endMs: 279_250,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示刷新按钮可用，金币足以刷新，且刷新前商店内容完整可见。",
    actionStatement: "玩家明确点击刷新，金币减少1并出现一整排新的商店内容。",
    reviewRationale: "按钮点击、金币减少1和整店更换共同构成直接刷新证据。",
    visible: { refreshCurrency: "gold", refreshCost: 1 },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新按钮显示1费且金币余额足够，刷新与停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "金币减少1且整店内容更换，直接证明执行一次刷新。",
      },
    ],
  },
  // BV16q3z66Euu
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv16q3z66euu-155900-combat",
    bvid: "BV16q3z66Euu",
    startMs: 155_200,
    decisionMs: 155_900,
    endMs: 156_200,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合4、等级3、0/6金币、30生命6护甲、场上2个和手牌2张。",
    actionStatement: "商店保持未冻结，倒计时结束后画面明确切换到“开始战斗”。",
    reviewRationale: "0费冻结按钮、未冻结商店和战斗阶段切换构成明确负样本边界。",
    visible: {
      round: 4,
      tavernTier: 3,
      health: 30,
      armor: 6,
      gold: 0,
      boardSize: 2,
      handSize: 2,
      upgradeCost: 10,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.96,
        legalStatement: "冻结按钮显示0费且商店未冻结，结束回合前冻结仍合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "招募阶段明确结束并进入战斗且商店未结冰，因此选择保持未冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv16q3z66euu-289100-upgrade",
    bvid: "BV16q3z66Euu",
    startMs: 288_200,
    decisionMs: 289_100,
    endMs: 290_000,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合6、等级4、8/8金币、19生命0护甲、场上6个和手牌7张。",
    actionStatement: "玩家明确点击酒馆升级，金币由8变为0且酒馆由等级4升到5。",
    reviewRationale: "升级按钮、费用、点击以及升级后的金币和等级均清晰可见。",
    visible: {
      round: 6,
      tavernTier: 4,
      health: 19,
      armor: 0,
      gold: 8,
      boardSize: 6,
      handSize: 7,
      upgradeCost: 8,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为8且玩家有8金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击、金币归零和等级变化直接证明立即升级。",
      },
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.98,
        legalStatement: "刷新费用为1且玩家有8金币，刷新原本合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 8,
          after: 0,
          required: 1,
        },
        interpretation: "玩家明确花尽金币升级且商店未重掷，因此选择停止刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv16q3z66euu-482800-refresh-over-upgrade",
    bvid: "BV16q3z66Euu",
    startMs: 482_500,
    decisionMs: 482_800,
    endMs: 483_200,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示回合8、等级5、9/10金币、升级费用9且刷新费用为1。",
    actionStatement: "玩家明确点击刷新，金币由9变为8且完整商店内容发生更换。",
    reviewRationale: "刷新按钮、1点金币扣除和整店更换直接证明刷新；扣费后余额低于升级费用。",
    visible: {
      round: 8,
      tavernTier: 5,
      gold: 9,
      upgradeCost: 9,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有9金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "金币减少1且完整商店更换，直接证明执行一次刷新。",
      },
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.99,
        legalStatement: "升级费用为9且玩家有9金币，动作前立即升级合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 9,
          after: 8,
          required: 9,
        },
        interpretation: "1费刷新使金币由9降至8，升级在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv16q3z66euu-603500-refresh",
    bvid: "BV16q3z66Euu",
    startMs: 603_000,
    decisionMs: 603_500,
    endMs: 604_000,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示回合9、等级5、13/10金币、升级费用8且刷新费用为1。",
    actionStatement: "玩家明确点击刷新，金币由13变为12且整排商店内容更换。",
    reviewRationale: "刷新提示、金币扣除和完整的新商店在连续帧中清晰可见。",
    visible: {
      round: 9,
      tavernTier: 5,
      gold: 13,
      upgradeCost: 8,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有13金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少1且完整商店更换，直接证明执行一次刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv16q3z66euu-612700-upgrade",
    bvid: "BV16q3z66Euu",
    startMs: 612_000,
    decisionMs: 612_700,
    endMs: 613_200,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合9、等级5、12/10金币且升级费用为8。",
    actionStatement: "玩家明确点击酒馆升级，金币由12变为4且酒馆由等级5升到6。",
    reviewRationale: "升级提示、按钮点击、8点金币扣除和等级变化均由连续帧直接支持。",
    visible: {
      round: 9,
      tavernTier: 5,
      gold: 12,
      upgradeCost: 8,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为8且玩家有12金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击、金币减少8和等级5到6直接证明立即升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv16q3z66euu-900600-freeze",
    bvid: "BV16q3z66Euu",
    startMs: 900_300,
    decisionMs: 900_600,
    endMs: 901_500,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合11、等级6、0/10金币、19生命0护甲、场上5个、手牌4张和7格商店。",
    actionStatement: "光标停在冻结按钮并显示冻结提示，随后7个商店实体全部结冰。",
    reviewRationale: "冻结按钮提示、点击后的冰霜波和完整结冰结果均清晰可见。",
    visible: {
      round: 11,
      tavernTier: 6,
      health: 19,
      armor: 0,
      gold: 0,
      boardSize: 5,
      handSize: 4,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.99,
        legalStatement: "冻结按钮显示0费且商店此前未冻结，冻结和保持未冻结均合法。",
        evidenceMode: "direct",
        interpretation: "按钮提示和完整结冰动画直接证明选择冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv16q3z66euu-1019600-refresh",
    bvid: "BV16q3z66Euu",
    startMs: 1_019_300,
    decisionMs: 1_019_600,
    endMs: 1_020_300,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示回合12、等级6、6/10金币、19生命0护甲、场上7个、手牌1张和5格商店。",
    actionStatement: "玩家明确点击刷新，金币由6变为5且商店从剩余5格换为新的7格内容。",
    reviewRationale: "刷新按钮点击、金币扣除和整店更换在连续帧中清晰可见。",
    visible: {
      round: 12,
      tavernTier: 6,
      health: 19,
      armor: 0,
      gold: 6,
      boardSize: 7,
      handSize: 1,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有6金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "金币减少1并出现完整新商店，直接证明执行一次刷新。",
      },
    ],
  },

  // BV1GCNT6REBk
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1gcnt6rebk-120700-buy-over-upgrade",
    bvid: "BV1GCNT6REBk",
    startMs: 119_500,
    decisionMs: 120_700,
    endMs: 121_700,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合4、等级3、6金币、升级费用5、30生命9护甲和场上3个随从。",
    actionStatement: "玩家明确购买一个商店随从，金币由6变为3且场上数量由3变为4。",
    reviewRationale: "合法升级状态和清晰的购买、金币及场面变化构成互斥边界。",
    visible: {
      round: 4,
      tavernTier: 3,
      health: 30,
      armor: 9,
      gold: 6,
      boardSize: 3,
      upgradeCost: 5,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.99,
        legalStatement: "升级费用为5且玩家有6金币，立即升级原本合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 6,
          after: 3,
          required: 5,
        },
        interpretation: "玩家明确购买随从并使金币降至3，因此该动作边界选择暂缓升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1gcnt6rebk-133800-refresh",
    bvid: "BV1GCNT6REBk",
    startMs: 132_500,
    decisionMs: 133_800,
    endMs: 134_700,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示回合4、等级3、4金币、30生命9护甲、场上4个和手牌2张法术。",
    actionStatement: "玩家明确点击1费刷新，金币由4变为3且整排商店内容更换。",
    reviewRationale: "按钮点击、金币扣除和新旧商店内容在连续帧中清晰可见。",
    visible: {
      round: 4,
      tavernTier: 3,
      health: 30,
      armor: 9,
      gold: 4,
      boardSize: 4,
      handSize: 2,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有4金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少1且整店更换，直接证明执行一次刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1gcnt6rebk-183100-upgrade",
    bvid: "BV1GCNT6REBk",
    startMs: 182_200,
    decisionMs: 183_100,
    endMs: 184_700,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合5、等级3、8金币、升级费用7、30生命3护甲、场上5个和手牌1张。",
    actionStatement: "玩家明确点击升级，金币由8变为1且酒馆等级由3变为4。",
    reviewRationale: "升级按钮、点击、金币8到1及等级3到4均直接可见。",
    visible: {
      round: 5,
      tavernTier: 3,
      health: 30,
      armor: 3,
      gold: 8,
      boardSize: 5,
      handSize: 1,
      upgradeCost: 7,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为7且玩家有8金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击、金币扣除和等级变化直接证明立即升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1gcnt6rebk-252800-buy-over-refresh",
    bvid: "BV1GCNT6REBk",
    startMs: 252_300,
    decisionMs: 252_800,
    endMs: 253_500,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合6、等级4、3金币、28生命、场上6个随从和1费刷新按钮。",
    actionStatement: "玩家明确购买一个商店随从，金币由3变为0且商店没有重掷。",
    reviewRationale: "合法刷新按钮和金币3到0的购买动作构成明确互斥边界。",
    visible: {
      round: 6,
      tavernTier: 4,
      health: 28,
      gold: 3,
      boardSize: 6,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.97,
        legalStatement: "玩家有3金币且刷新费用为1，刷新原本合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 3,
          after: 0,
          required: 1,
        },
        interpretation: "玩家明确花费3金币购买随从并未重掷商店，因此选择停止刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1gcnt6rebk-342000-upgrade",
    bvid: "BV1GCNT6REBk",
    startMs: 341_300,
    decisionMs: 342_000,
    endMs: 343_300,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合7、等级4、12金币、升级费用9、28生命和场上6个随从。",
    actionStatement: "玩家明确点击酒馆升级，金币由12变为3且等级由4变为5。",
    reviewRationale: "升级按钮、费用、金币扣除和等级变化均在连续帧中可见。",
    visible: {
      round: 7,
      tavernTier: 4,
      health: 28,
      gold: 12,
      boardSize: 6,
      upgradeCost: 9,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为9且玩家有12金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少9且等级升到5，直接证明立即升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1gcnt6rebk-356700-combat-unfrozen",
    bvid: "BV1GCNT6REBk",
    startMs: 354_800,
    decisionMs: 356_700,
    endMs: 357_300,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合7、等级5、0金币、28生命、场上7个、手牌1张且商店未冻结。",
    actionStatement: "玩家保持商店未冻结，招募阶段随后明确切换至战斗。",
    reviewRationale: "0费合法冻结按钮、持续未冻结状态和战斗切换构成负样本边界。",
    visible: {
      round: 7,
      tavernTier: 5,
      health: 28,
      gold: 0,
      boardSize: 7,
      handSize: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.98,
        legalStatement: "冻结按钮为0费且商店未冻结，回合结束前冻结仍合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "招募阶段明确结束且商店未结冰，因此选择保持未冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1gcnt6rebk-576000-freeze",
    bvid: "BV1GCNT6REBk",
    startMs: 575_500,
    decisionMs: 576_000,
    endMs: 576_700,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合9、1金币、13生命、场上7个和手牌8张，冻结按钮可用。",
    actionStatement: "商店出现清晰的结冰状态，并在随后的战斗边界前保持冻结。",
    reviewRationale: "连续帧中的结冰结果和保持到战斗的状态直接支持冻结标签。",
    visible: { round: 9, health: 13, gold: 1, boardSize: 7, handSize: 8 },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.99,
        legalStatement: "冻结按钮在招募阶段可用，冻结与不冻结均为合法选择。",
        evidenceMode: "direct",
        interpretation: "可见的整店结冰及其保持到战斗直接证明选择冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1gcnt6rebk-831100-freeze",
    bvid: "BV1GCNT6REBk",
    startMs: 830_500,
    decisionMs: 831_100,
    endMs: 831_700,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合11、3金币、13生命5护甲、场上5个和手牌7张，冻结按钮可用。",
    actionStatement: "连续画面显示商店实体出现明确的结冰视觉效果。",
    reviewRationale: "冻结前后的连续状态和完整结冰结果直接支持冻结标签。",
    visible: {
      round: 11,
      health: 13,
      armor: 5,
      gold: 3,
      boardSize: 5,
      handSize: 7,
    },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.98,
        legalStatement: "冻结按钮在招募阶段清晰可用，冻结与不冻结均为合法选择。",
        evidenceMode: "direct",
        interpretation: "可见的商店结冰结果直接证明选择冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1gcnt6rebk-1071200-freeze",
    bvid: "BV1GCNT6REBk",
    startMs: 1_070_500,
    decisionMs: 1_071_200,
    endMs: 1_071_800,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合13、1金币、13生命5护甲、场上7个和手牌4张，冻结按钮可用。",
    actionStatement: "连续帧显示商店实体由未结冰状态变为完整结冰状态。",
    reviewRationale: "冻结前后状态变化清晰且没有同时发生的法术或随从效果。",
    visible: {
      round: 13,
      health: 13,
      armor: 5,
      gold: 1,
      boardSize: 7,
      handSize: 4,
    },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.99,
        legalStatement: "冻结按钮在招募阶段清晰可用，冻结与不冻结均为合法选择。",
        evidenceMode: "direct",
        interpretation: "商店由未结冰变为完整结冰，直接证明选择冻结。",
      },
    ],
  },

  // BV1FvNR6iEEP
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1fvnr6ieep-068200-upgrade",
    bvid: "BV1FvNR6iEEP",
    startMs: 67_000,
    decisionMs: 68_200,
    endMs: 69_000,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合2、等级1、4金币、升级费用4、30生命15护甲、场上1个且手牌为空。",
    actionStatement: "玩家明确点击升级，金币由4变为0、等级由1变为2且下次升级费用变为7。",
    reviewRationale: "升级按钮、点击、金币归零和等级变化均在连续帧中清晰可见。",
    visible: {
      round: 2,
      tavernTier: 1,
      health: 30,
      armor: 15,
      gold: 4,
      boardSize: 1,
      handSize: 0,
      upgradeCost: 4,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为4且玩家有4金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币归零且等级由1变为2，直接证明立即升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1fvnr6ieep-172650-upgrade",
    bvid: "BV1FvNR6iEEP",
    startMs: 172_200,
    decisionMs: 172_650,
    endMs: 173_200,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合5、等级2、7金币、升级费用4、30生命11护甲、场上5个和手牌1张。",
    actionStatement: "玩家明确点击升级，金币由7变为3、等级由2变为3且下次升级费用变为8。",
    reviewRationale: "升级费用、按钮点击、金币扣除和等级变化均直接可见。",
    visible: {
      round: 5,
      tavernTier: 2,
      health: 30,
      armor: 11,
      gold: 7,
      boardSize: 5,
      handSize: 1,
      upgradeCost: 4,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为4且玩家有7金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少4且等级由2变为3，直接证明立即升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1fvnr6ieep-225250-upgrade-over-refresh",
    bvid: "BV1FvNR6iEEP",
    startMs: 224_750,
    decisionMs: 225_250,
    endMs: 226_000,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合6、等级3、7金币、升级费用7、30生命11护甲、场上6个和手牌4张。",
    actionStatement: "玩家明确点击升级，金币由7变为0、等级由3变为4且没有刷新商店。",
    reviewRationale: "合法刷新状态和明确升级动作构成互斥边界，商店没有重掷。",
    visible: {
      round: 6,
      tavernTier: 3,
      health: 30,
      armor: 11,
      gold: 7,
      boardSize: 6,
      handSize: 4,
      upgradeCost: 7,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.98,
        legalStatement: "刷新费用为1且玩家有7金币，刷新原本合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 7,
          after: 0,
          required: 1,
        },
        interpretation: "玩家明确花尽金币升级且商店未重掷，因此选择停止刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1fvnr6ieep-251250-freeze",
    bvid: "BV1FvNR6iEEP",
    startMs: 250_750,
    decisionMs: 251_250,
    endMs: 251_750,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合6、等级4、0金币、30生命11护甲、场上7个、空手和7格未冻结商店。",
    actionStatement: "玩家明确点击0费冻结按钮，随后7个商店实体全部出现冰层。",
    reviewRationale: "冻结前状态、按钮点击和完整结冰结果均由连续帧直接支持。",
    visible: {
      round: 6,
      tavernTier: 4,
      health: 30,
      armor: 11,
      gold: 0,
      boardSize: 7,
      handSize: 0,
      upgradeCost: 11,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.99,
        legalStatement: "冻结按钮为0费且商店此前未冻结，冻结与保持未冻结均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击后的整店结冰结果直接证明选择冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1fvnr6ieep-415250-upgrade",
    bvid: "BV1FvNR6iEEP",
    startMs: 414_750,
    decisionMs: 415_250,
    endMs: 416_500,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合8、等级4、14金币、升级费用9、30生命1护甲、场上7个和手牌7张。",
    actionStatement: "玩家明确点击升级，金币由14变为5、等级由4变为5且下次升级费用变为11。",
    reviewRationale: "升级按钮、点击、金币扣除和等级变化均在连续帧中清晰可见。",
    visible: {
      round: 8,
      tavernTier: 4,
      health: 30,
      armor: 1,
      gold: 14,
      boardSize: 7,
      handSize: 7,
      upgradeCost: 9,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为9且玩家有14金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少9且等级由4变为5，直接证明立即升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1fvnr6ieep-428250-refresh",
    bvid: "BV1FvNR6iEEP",
    startMs: 427_750,
    decisionMs: 428_250,
    endMs: 429_750,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示回合8、等级5、7金币、30生命1护甲、场上7个、手牌3张和7格商店。",
    actionStatement: "玩家明确点击1费刷新，金币由7变为6且7格商店全部更换。",
    reviewRationale: "刷新按钮、金币减少1和整店更换在连续帧中直接可见。",
    visible: {
      round: 8,
      tavernTier: 5,
      health: 30,
      armor: 1,
      gold: 7,
      boardSize: 7,
      handSize: 3,
      upgradeCost: 11,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有7金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少1且7格商店全部更换，直接证明刷新一次。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1fvnr6ieep-929250-refresh",
    bvid: "BV1FvNR6iEEP",
    startMs: 928_900,
    decisionMs: 929_250,
    endMs: 930_250,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示回合12、等级5、10金币、30生命1护甲、场上7个、手牌4张和7格商店。",
    actionStatement: "玩家明确点击1费刷新，金币由10变为9且7格商店全部更换。",
    reviewRationale: "刷新点击、金币减少1和完整新商店均由连续帧直接支持。",
    visible: {
      round: 12,
      tavernTier: 5,
      health: 30,
      armor: 1,
      gold: 10,
      boardSize: 7,
      handSize: 4,
      upgradeCost: 7,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有10金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少1且7格商店全部更换，直接证明刷新一次。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1fvnr6ieep-937250-buy-over-upgrade",
    bvid: "BV1FvNR6iEEP",
    startMs: 936_250,
    decisionMs: 937_250,
    endMs: 937_750,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合12、等级5、9金币、升级费用7、30生命1护甲、场上7个和手牌3张。",
    actionStatement: "玩家明确购买一个3费商店随从，金币由9变为6、手牌增至4张且商店少1格。",
    reviewRationale: "购买动作使升级由可支付变为不可支付，构成明确的互斥选择边界。",
    visible: {
      round: 12,
      tavernTier: 5,
      health: 30,
      armor: 1,
      gold: 9,
      boardSize: 7,
      handSize: 3,
      upgradeCost: 7,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.98,
        legalStatement: "升级费用为7且玩家有9金币，购买前立即升级合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 9,
          after: 6,
          required: 7,
        },
        interpretation: "玩家明确花3金币购买随从并使余额降至6，因此选择暂缓升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1fvnr6ieep-974750-freeze",
    bvid: "BV1FvNR6iEEP",
    startMs: 973_750,
    decisionMs: 974_750,
    endMs: 975_250,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合12、等级5、1金币、30生命1护甲、场上6个、手牌2张和7格未冻结商店。",
    actionStatement: "玩家明确点击0费冻结按钮，随后7个商店实体全部出现冰层。",
    reviewRationale: "冻结前状态、按钮动作和完整结冰结果均在连续帧中清晰可见。",
    visible: {
      round: 12,
      tavernTier: 5,
      health: 30,
      armor: 1,
      gold: 1,
      boardSize: 6,
      handSize: 2,
      upgradeCost: 7,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.99,
        legalStatement: "冻结按钮为0费且商店此前未冻结，冻结与保持未冻结均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击后的整店结冰效果直接证明选择冻结。",
      },
    ],
  },

  // BV1TPN26RETm
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-106100-upgrade",
    bvid: "BV1TPN26RETm",
    startMs: 105_700,
    decisionMs: 106_100,
    endMs: 106_500,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合2、等级1、4/4金币、升级费用4、刷新费用1且商店未冻结。",
    actionStatement: "玩家明确点击酒馆升级，金币由4变为0且酒馆由等级1升到2。",
    reviewRationale: "升级按钮、点击、金币归零和等级变化直接证明升级；金币归零使刷新立即不合法。",
    visible: {
      round: 2,
      tavernTier: 1,
      health: 30,
      armor: 12,
      gold: 4,
      boardSize: 1,
      handSize: 0,
      upgradeCost: 4,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为4且玩家有4金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击、金币归零和等级1到2直接证明立即升级。",
      },
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.98,
        legalStatement: "刷新费用为1且玩家有4金币，动作前刷新合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 4,
          after: 0,
          required: 1,
        },
        interpretation: "升级花尽4金币，使刷新在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-126600-combat-unfrozen",
    bvid: "BV1TPN26RETm",
    startMs: 125_800,
    decisionMs: 126_600,
    endMs: 126_800,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合2、等级2、0/4金币、30生命12护甲、场上1个、空手和4格未冻结商店。",
    actionStatement: "商店保持完全未冻结，招募阶段结束后画面明确切换到战斗阶段。",
    reviewRationale: "未冻结商店和明确的招募到战斗阶段切换构成严格的负样本边界。",
    visible: {
      round: 2,
      tavernTier: 2,
      health: 30,
      armor: 12,
      gold: 0,
      boardSize: 1,
      handSize: 0,
      upgradeCost: 7,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.99,
        legalStatement: "冻结按钮为0费且商店未冻结，结束招募前冻结仍合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "商店保持未冻结并明确进入战斗，因此该回合选择不冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-164350-combat-unfrozen",
    bvid: "BV1TPN26RETm",
    startMs: 164_000,
    decisionMs: 164_350,
    endMs: 164_700,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合3、等级2、0/5金币、30生命10护甲、场上2个、手牌2张和未冻结商店。",
    actionStatement: "商店保持未冻结，招募阶段结束后画面明确切换到战斗阶段。",
    reviewRationale: "未冻结商店和明确的招募到战斗阶段切换构成严格的负样本边界。",
    visible: {
      round: 3,
      tavernTier: 2,
      health: 30,
      armor: 10,
      gold: 0,
      boardSize: 2,
      handSize: 2,
      upgradeCost: 6,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.99,
        legalStatement: "冻结按钮为0费且商店未冻结，结束招募前冻结仍合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "商店保持未冻结并明确进入战斗，因此该回合选择不冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-209200-freeze",
    bvid: "BV1TPN26RETm",
    startMs: 208_000,
    decisionMs: 209_200,
    endMs: 210_000,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合4、等级2、6/6金币、30生命7护甲、场上2个、手牌2张和5格商店。",
    actionStatement: "光标悬停0费冻结按钮，随后冰霜波扫过并使5个商店实体全部结冰。",
    reviewRationale: "按钮提示、点击后的冰霜动画和完整结冰结果均由连续帧支持。",
    visible: {
      round: 4,
      tavernTier: 2,
      health: 30,
      armor: 7,
      gold: 6,
      boardSize: 2,
      handSize: 2,
      upgradeCost: 5,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.99,
        legalStatement: "冻结按钮显示0费且商店此前未冻结，冻结和保持未冻结均合法。",
        evidenceMode: "direct",
        interpretation: "冻结按钮提示和整店结冰动画直接证明选择冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-216250-buy-over-upgrade",
    bvid: "BV1TPN26RETm",
    startMs: 216_000,
    decisionMs: 216_250,
    endMs: 216_625,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合4、酒馆等级2、6金币、30生命7护甲，升级费用为5且商店处于冻结状态。",
    actionStatement: "玩家明确购买商店中的3费2/2亡语随从，商店槽位减少且金币由6降至3，未进行升级。",
    reviewRationale: "购买动作、商店槽位变化及金币6到3共同构成清晰的升级互斥边界。",
    visible: {
      round: 4,
      tavernTier: 2,
      health: 30,
      armor: 7,
      gold: 6,
      boardSize: 2,
      upgradeCost: 5,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: true,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.99,
        legalStatement: "升级费用为5且玩家有6金币，购买前立即升级合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 6,
          after: 3,
          required: 5,
        },
        interpretation: "购买3费随从使金币降至3，升级在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-250500-upgrade",
    bvid: "BV1TPN26RETm",
    startMs: 250_000,
    decisionMs: 250_500,
    endMs: 251_000,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合5、等级2、7金币且酒馆升级费用为3。",
    actionStatement: "玩家明确点击酒馆升级，金币由7变为4且酒馆由等级2升到3。",
    reviewRationale: "升级按钮、点击、3点金币扣除和等级变化均由连续帧直接支持。",
    visible: {
      round: 5,
      tavernTier: 2,
      gold: 7,
      upgradeCost: 3,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为3且玩家有7金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击、金币减少3和等级2到3直接证明立即升级。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-329500-upgrade",
    bvid: "BV1TPN26RETm",
    startMs: 329_200,
    decisionMs: 329_500,
    endMs: 329_900,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "normalLevel",
    stateStatement: "画面显示回合6、等级3、7/8金币、30生命1护甲、场上3个、手牌2张和5格商店。",
    actionStatement: "玩家明确点击升级，金币由7变为0、等级由3变为4且下次升级费用变为11。",
    reviewRationale: "升级提示、按钮点击、金币归零和等级变化均在连续帧中清晰可见。",
    visible: {
      round: 6,
      tavernTier: 3,
      health: 30,
      armor: 1,
      gold: 7,
      boardSize: 3,
      handSize: 2,
      upgradeCost: 7,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "upgradeNow",
        confidence: 0.99,
        legalStatement: "升级费用为7且玩家有7金币，立即升级与暂缓均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击、金币归零和等级3到4直接证明立即升级。",
      },
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.98,
        legalStatement: "刷新费用为1且玩家有7金币，刷新原本合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 7,
          after: 0,
          required: 1,
        },
        interpretation: "玩家明确花尽金币升级且商店未重掷，因此选择停止刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-385400-combat-unfrozen",
    bvid: "BV1TPN26RETm",
    startMs: 384_000,
    decisionMs: 385_400,
    endMs: 385_700,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合6、等级4、0/8金币、30生命1护甲、满场7个、手牌3张和4格未冻结商店。",
    actionStatement: "商店保持完全未冻结，随后画面明确出现“开始战斗”并离开招募阶段。",
    reviewRationale: "未冻结商店和明确的招募到战斗阶段切换构成严格的负样本边界。",
    visible: {
      round: 6,
      tavernTier: 4,
      health: 30,
      armor: 1,
      gold: 0,
      boardSize: 7,
      handSize: 3,
      upgradeCost: 11,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.99,
        legalStatement: "冻结按钮为0费且商店未冻结，结束招募前冻结仍合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "商店保持未冻结并明确进入战斗，因此该回合选择不冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-603250-refresh",
    bvid: "BV1TPN26RETm",
    startMs: 603_100,
    decisionMs: 603_250,
    endMs: 603_800,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示回合9、等级6、5/10金币、30生命1护甲、满场7个、手牌10张和剩余6格商店。",
    actionStatement: "光标悬停刷新按钮并显示刷新说明，点击后金币由5变为4且出现新的7格商店。",
    reviewRationale: "刷新提示、金币扣除及完整的新商店在连续帧中直接可见。",
    visible: {
      round: 9,
      tavernTier: 6,
      health: 30,
      armor: 1,
      gold: 5,
      boardSize: 7,
      handSize: 10,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有5金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少1且商店由剩余6格换成新7格，直接证明刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-606150-refresh",
    bvid: "BV1TPN26RETm",
    startMs: 606_000,
    decisionMs: 606_150,
    endMs: 606_500,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "refresh",
    stateStatement: "画面显示回合9、等级6、4/10金币、刷新费用为1且商店有完整7格内容。",
    actionStatement: "玩家明确点击刷新，金币由4变为3且原商店清空并换入新的完整商店。",
    reviewRationale: "刷新提示、1点金币扣除和整店更换均在连续帧中清晰可见。",
    visible: {
      round: 9,
      tavernTier: 6,
      gold: 4,
      refreshCurrency: "gold",
      refreshCost: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "refresh",
        choice: "refreshOnce",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有4金币，刷新和停止刷新均合法。",
        evidenceMode: "direct",
        interpretation: "点击后金币减少1且完整商店更换，直接证明执行一次刷新。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1tpn26retm-697500-combat-unfrozen",
    bvid: "BV1TPN26RETm",
    startMs: 696_900,
    decisionMs: 697_500,
    endMs: 697_750,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合9、等级6、0/10金币和5格完全未冻结的商店。",
    actionStatement: "商店保持完全未冻结，随后画面明确出现“开始战斗”并离开招募阶段。",
    reviewRationale: "697.25秒仍为未冻结招募画面，697.50秒明确进入战斗，构成严格负样本边界。",
    visible: {
      round: 9,
      tavernTier: 6,
      gold: 0,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.99,
        legalStatement: "冻结按钮为0费且商店未冻结，结束招募前冻结仍合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "商店保持未冻结并明确进入战斗，因此该回合选择不冻结。",
      },
    ],
  },
  // BV1w9Ti6tEMq
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1w9ti6temq-044000-freeze",
    bvid: "BV1w9Ti6tEMq",
    startMs: 43_750,
    decisionMs: 44_000,
    endMs: 44_500,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合1、0金币、30生命10护甲、场上1个随从，商店在操作前没有冰层。",
    actionStatement: "玩家明确点击0费冻结按钮，随后商店中的实体全部出现结冰效果。",
    reviewRationale: "冻结前状态、按钮点击及整店结冰结果均由连续帧直接支持。",
    visible: {
      round: 1,
      health: 30,
      armor: 10,
      gold: 0,
      boardSize: 1,
      currentlyFrozen: false,
    },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.99,
        legalStatement: "冻结按钮显示0费且商店此前未冻结，冻结和保持未冻结均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击后的整店结冰动画直接证明选择冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1w9ti6temq-123500-hero-power-over-upgrade",
    bvid: "BV1w9Ti6tEMq",
    startMs: 122_750,
    decisionMs: 123_500,
    endMs: 124_250,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合4、酒馆等级2、6金币且升级费用为5，立即升级原本合法。",
    actionStatement: "玩家明确花费2金币使用英雄技能获得一个随从，金币由6降至4。",
    reviewRationale: "可见的2费英雄技能操作使金币跨过5费升级的合法边界。",
    visible: {
      round: 4,
      tavernTier: 2,
      health: 30,
      armor: 10,
      gold: 6,
      boardSize: 3,
      handSize: 1,
      upgradeCost: 5,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.99,
        legalStatement: "升级费用为5且玩家有6金币，动作前立即升级合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 6,
          after: 4,
          required: 5,
        },
        interpretation: "使用2费英雄技能使金币降至4，升级在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1w9ti6temq-146625-combat-unfrozen",
    bvid: "BV1w9Ti6tEMq",
    startMs: 146_500,
    decisionMs: 146_625,
    endMs: 146_750,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "招募阶段结束前，画面中的商店保持完全未冻结。",
    actionStatement: "玩家没有点击冻结，未冻结商店随后明确切换到战斗阶段。",
    reviewRationale: "未冻结商店和紧邻的招募到战斗阶段切换构成严格负样本边界。",
    visible: { currentlyFrozen: false },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.99,
        legalStatement: "商店未冻结且0费冻结动作在招募阶段结束前仍然合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "商店保持未冻结并明确进入战斗，因此该回合选择不冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1w9ti6temq-214625-combat-unfrozen",
    bvid: "BV1w9Ti6tEMq",
    startMs: 214_500,
    decisionMs: 214_625,
    endMs: 214_750,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "招募阶段结束前，画面中的商店保持完全未冻结。",
    actionStatement: "玩家没有点击冻结，未冻结商店随后明确切换到战斗阶段。",
    reviewRationale: "未冻结商店和紧邻的招募到战斗阶段切换构成严格负样本边界。",
    visible: { currentlyFrozen: false },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.99,
        legalStatement: "商店未冻结且0费冻结动作在招募阶段结束前仍然合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "商店保持未冻结并明确进入战斗，因此该回合选择不冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1w9ti6temq-291750-combat-unfrozen",
    bvid: "BV1w9Ti6tEMq",
    startMs: 291_500,
    decisionMs: 291_750,
    endMs: 292_000,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "招募阶段结束前，画面中的商店保持完全未冻结。",
    actionStatement: "玩家没有点击冻结，未冻结商店随后明确切换到战斗阶段。",
    reviewRationale: "未冻结商店和紧邻的招募到战斗阶段切换构成严格负样本边界。",
    visible: { currentlyFrozen: false },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.99,
        legalStatement: "商店未冻结且0费冻结动作在招募阶段结束前仍然合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "商店保持未冻结并明确进入战斗，因此该回合选择不冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1w9ti6temq-465125-buy-over-refresh",
    bvid: "BV1w9Ti6tEMq",
    startMs: 465_000,
    decisionMs: 465_125,
    endMs: 465_250,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示玩家有3/10金币且刷新费用为1，刷新在购买前合法。",
    actionStatement: "玩家明确购买商店中的3费3/8随从，金币由3降至0。",
    reviewRationale: "可见的3费购买使金币跨过1费刷新的合法边界。",
    visible: {
      gold: 3,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有3金币，动作前刷新合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 3,
          after: 0,
          required: 1,
        },
        interpretation: "购买3费随从使金币降至0，刷新在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1w9ti6temq-474750-freeze",
    bvid: "BV1w9Ti6tEMq",
    startMs: 474_500,
    decisionMs: 474_750,
    endMs: 475_250,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "操作前商店实体没有冰层，画面中的0费冻结按钮处于可用状态。",
    actionStatement: "玩家明确点击冻结按钮，随后商店实体出现完整的结冰效果。",
    reviewRationale: "冻结前状态、按钮点击及结冰结果均由连续帧直接支持。",
    visible: { currentlyFrozen: false },
    labels: [
      {
        kind: "freeze",
        choice: "freeze",
        confidence: 0.99,
        legalStatement: "冻结按钮显示0费且商店此前未冻结，冻结和保持未冻结均合法。",
        evidenceMode: "direct",
        interpretation: "按钮点击后的整店结冰动画直接证明选择冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1w9ti6temq-781625-combat-unfrozen",
    bvid: "BV1w9Ti6tEMq",
    startMs: 781_500,
    decisionMs: 781_625,
    endMs: 781_750,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "endTurn",
    stateStatement: "画面显示回合10、0金币，招募阶段结束前商店保持完全未冻结。",
    actionStatement: "玩家没有点击冻结，未冻结商店随后明确切换到战斗阶段。",
    reviewRationale: "未冻结商店和紧邻的招募到战斗阶段切换构成严格负样本边界。",
    visible: { round: 10, gold: 0, currentlyFrozen: false },
    labels: [
      {
        kind: "freeze",
        choice: "unfreeze",
        confidence: 0.99,
        legalStatement: "商店未冻结且0费冻结动作在招募阶段结束前仍然合法。",
        evidenceMode: "inferred",
        inferredBoundary: { kind: "recruitToCombat" },
        interpretation: "商店保持未冻结并明确进入战斗，因此该回合选择不冻结。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1w9ti6temq-1418375-buy-over-refresh",
    bvid: "BV1w9Ti6tEMq",
    startMs: 1_418_250,
    decisionMs: 1_418_375,
    endMs: 1_418_500,
    reviewedBy: AI_VIDEO_CORPUS_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合15、酒馆等级5、3金币且刷新费用为1，刷新在购买前合法。",
    actionStatement: "玩家明确购买商店最左侧的3费随从，金币由3降至0。",
    reviewRationale: "可见的3费购买使金币跨过1费刷新的合法边界。",
    visible: {
      round: 15,
      tavernTier: 5,
      gold: 3,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有3金币，动作前刷新合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 3,
          after: 0,
          required: 1,
        },
        interpretation: "购买3费随从使金币降至0，刷新在该动作边界后立即失去合法性。",
      },
    ],
  },
  // BV1y1VD6DEj7
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1y1vd6dej7-061375-buy-over-refresh",
    bvid: "BV1y1VD6DEj7",
    startMs: 61_350,
    decisionMs: 61_375,
    endMs: 61_500,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合1、酒馆等级1、3金币、30生命11护甲，刷新费用为1且升级费用为5。",
    actionStatement: "玩家明确购买商店中的3费随从，随从进入手牌且金币由3降至0。",
    reviewRationale: "购买动作、手牌变化及金币3到0共同构成清晰的刷新互斥边界。",
    visible: {
      round: 1,
      tavernTier: 1,
      health: 30,
      armor: 11,
      gold: 3,
      boardSize: 0,
      upgradeCost: 5,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有3金币，购买前刷新合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 3,
          after: 0,
          required: 1,
        },
        interpretation: "购买3费随从使金币降至0，刷新在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1y1vd6dej7-132688-action-over-upgrade",
    bvid: "BV1y1VD6DEj7",
    startMs: 132_625,
    decisionMs: 132_688,
    endMs: 132_750,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合4、酒馆等级2、6金币、30生命6护甲，升级费用为5且刷新费用为1。",
    actionStatement: "玩家明确执行一项非升级的3金币取牌动作，金币由6降至3且升级按钮未被触发。",
    reviewRationale: "可见的非升级3金币动作使金币跨过5费升级的合法边界。",
    visible: {
      round: 4,
      tavernTier: 2,
      health: 30,
      armor: 6,
      gold: 6,
      boardSize: 2,
      upgradeCost: 5,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.99,
        legalStatement: "升级费用为5且玩家有6金币，动作前立即升级合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 6,
          after: 3,
          required: 5,
        },
        interpretation: "非升级动作使金币降至3，升级在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1y1vd6dej7-144688-spell-over-refresh",
    bvid: "BV1y1VD6DEj7",
    startMs: 144_625,
    decisionMs: 144_688,
    endMs: 144_750,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合4、酒馆等级2、1金币、30生命6护甲，刷新费用为1且升级费用为5。",
    actionStatement: "玩家明确购买1费酒馆法术，金币由1降至0且商店法术槽位发生变化。",
    reviewRationale: "1费法术购买及金币1到0共同构成清晰的刷新互斥边界。",
    visible: {
      round: 4,
      tavernTier: 2,
      health: 30,
      armor: 6,
      gold: 1,
      boardSize: 4,
      upgradeCost: 5,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有1金币，购买前刷新合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 1,
          after: 0,
          required: 1,
        },
        interpretation: "购买1费酒馆法术使金币降至0，刷新在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1y1vd6dej7-171875-buy-over-refresh",
    bvid: "BV1y1VD6DEj7",
    startMs: 171_750,
    decisionMs: 171_875,
    endMs: 172_000,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合5、酒馆等级3、3金币、30生命6护甲，刷新费用为1且升级费用为8。",
    actionStatement: "玩家明确购买商店中的3费随从，商店槽位减少且金币由3降至0。",
    reviewRationale: "3费随从购买及金币3到0共同构成清晰的刷新互斥边界。",
    visible: {
      round: 5,
      tavernTier: 3,
      health: 30,
      armor: 6,
      gold: 3,
      boardSize: 4,
      upgradeCost: 8,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "refresh",
        choice: "stopRefreshing",
        confidence: 0.99,
        legalStatement: "刷新费用为1且玩家有3金币，购买前刷新合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 3,
          after: 0,
          required: 1,
        },
        interpretation: "购买3费随从使金币降至0，刷新在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1y1vd6dej7-289125-action-over-upgrade",
    bvid: "BV1y1VD6DEj7",
    startMs: 289_000,
    decisionMs: 289_125,
    endMs: 289_250,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合8、酒馆等级5、11生命、10金币，升级费用为10且刷新费用为1。",
    actionStatement: "玩家明确执行一项非升级的3金币动作，金币由10降至7；升级按钮未触发且商店未重掷。",
    reviewRationale: "动作身份部分被悬浮信息遮挡，但非升级动作、3点金币扣除及升级按钮状态均清晰可见。",
    visible: {
      round: 8,
      tavernTier: 5,
      health: 11,
      gold: 10,
      boardSize: 4,
      upgradeCost: 10,
      refreshCurrency: "gold",
      refreshCost: 1,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.99,
        legalStatement: "升级费用为10且玩家有10金币，动作前立即升级合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 10,
          after: 7,
          required: 10,
        },
        interpretation: "明确的非升级3金币动作使余额降至7，升级在该动作边界后立即失去合法性。",
      },
    ],
  },
  {
    schemaVersion: AI_VIDEO_DECISION_CORPUS_SCHEMA_VERSION,
    windowId: "bv1y1vd6dej7-305250-spell-over-upgrade",
    bvid: "BV1y1VD6DEj7",
    startMs: 305_000,
    decisionMs: 305_250,
    endMs: 305_500,
    reviewedBy: AI_VIDEO_CORPUS_DOUBLE_REVIEWER,
    chosenPlan: "tempo",
    stateStatement: "画面显示回合8、酒馆等级5、11生命、10金币且升级费用为10。",
    actionStatement: "玩家明确购买1费酒馆法术，法术槽位发生变化且金币由10降至9。",
    reviewRationale: "1费酒馆法术购买使金币跨过10费升级的合法边界。",
    visible: {
      round: 8,
      tavernTier: 5,
      health: 11,
      gold: 10,
      boardSize: 7,
      upgradeCost: 10,
      refreshCurrency: "gold",
      refreshCost: 0,
    },
    labels: [
      {
        kind: "upgrade",
        choice: "deferUpgrade",
        confidence: 0.99,
        legalStatement: "升级费用为10且玩家有10金币，购买前立即升级合法。",
        evidenceMode: "inferred",
        inferredBoundary: {
          kind: "resourceBecameInsufficient",
          before: 10,
          after: 9,
          required: 10,
        },
        interpretation: "购买1费酒馆法术使金币降至9，升级在该动作边界后立即失去合法性。",
      },
    ],
  },
] satisfies readonly AiVideoDecisionWindow[]);

export const AI_VIDEO_DECISION_CORPUS = buildAiVideoDecisionCorpus(
  AI_VIDEO_DECISION_WINDOWS,
);

export const AI_VIDEO_EXPERT_SAMPLES =
  AI_VIDEO_DECISION_CORPUS.expertSamples;

export const AI_VIDEO_TRAINING_EXAMPLES =
  AI_VIDEO_DECISION_CORPUS.trainingExamples;
